version: '2'
services:
  ldap:
    image: osixia/openldap:1.2.2
    container_name: kiss-ldap
    volumes:
      - $PWD/config:/etc/ldap/slapd.d
      - $PWD/data:/var/lib/ldap
    environment:
      - LDAP_ORGANISATION=KissCloud
      - LDAP_DOMAIN=kisscloud.io
      - LDAP_ADMIN_PASSWORD=kisscloud  
    ports:
      - 389:389
